# Copyright 2014 MERCIER David
# Be careful to put a comma + a space between each data...! (YAML convention)
#################################################################################
# Semi-angle from the apex (in degrees) and equivalent cone angle (in degrees)
theta_Berkovich: 65.3
thetaeq_Berkovich: 70.32
theta_Vickers: 68
thetaeq_Vickers: 70.2996
theta_CubeCorner: 35.2644
thetaeq_CubeCorner: 42.286

#################################################################################
# List of indenters
# For user_defined indenters, make the name of the indenter begins with the 4th first letters of the indenters
# e.g. : Berk_TB10161_091208 or Coni_120812 or Vick120512_oldtip or CubeCornerXXXFFF
Indenter_IDs: [Berkovich, Vickers, CubeCorner, Conical, Berko_Example]
# Set the indenter you want to use by default
Indenter_ID: Berko_Example

#################################################################################
# List of indenter's material - !!! Do not remove !!!
Indenter_materials: [Diamond, Sapphire]
# Material properties [Young's modulus in GPa, Poisson's ratio] from A.C. Fischer-Cripps "Nanoindentation" - Springer 2nd Ed. (2004)
Indenter_material_properties: {Diamond: [1070, 0.07], Sapphire: [400, 0.25]}
# Default indenter's material
Indenter_material: Diamond

#################################################################################
# !!! Do not remove !!!
# For Berkovich, Vickers and Cube-Corner : [C0, C1, C2, C3, C4, C5, C6, C7, C8, Tip defect in nm, Semi-angle in degrees]
# If C0 is not given (=0), the semi-angle from the apex has to be given in degrees and C0 will be calculated using the formulae for a perfect conical indenter.
# C0 to C8 are coefficients from the function area defined by Oliver et al. (1992) - DOI: 10.1557/JMR.1992.1564
# Use the same indenter name as given in the list of indenters !!!
Berkovich: [24.56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Vickers: [20.50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
CubeCorner: [2.598, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Conical: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 45]
Berko_Example: [23.58, 1173.55, -4230.85, 2172.3, 0, 0, 0, 0, 0, 0, 0]