# Copyright 2014 MERCIER David
# Be careful to put a comma + a space between each data...! (YAML convention)
###########################################################################################
# Constant given by Hochstetter et al. (1999) - DOI: 10.1080/00222349908248131 
# and Bec et al. (2006) - DOI: 10.1080/01418619608239707
alpha_Loubet: 1.24

###########################################################################################
# Constants given by Oliver et al. (1992) - DOI: 10.1557/JMR.1992.1564
epsilonParaboloidRevolution_OliverPharr: 0.75
epsilonConical_OliverPharr: 0.72
epsilonFlatPunch_OliverPharr: 1

# Constants given by Merle et al. (2012) - DOI: 10.1557/jmr.2011.245
epsilon_Merle: 0.76

###########################################################################################
# Constants given by King (1987) - DOI: 10.1016/0020-7683(87)90116-8
betaBerkovich_King: 1.034
betaVickers_King: 1.012
betaConical_King: 1.000

# Constants given by Troyon et al. (2002) - DOI: 10.1080/14786430600606834
betaBerkovich_Troyon: 1.062

###########################################################################################
# CSM correction - Constants given by Pharr et al. (2009) - DOI: 10.1557/jmr.2009.0096
CSM_K_Pharr: 0.757
CSM_m_Pharr: 1.380

###########################################################################################
# Constants given by Li et al. (2010) - DOI: 10.1557/JMR.2010.0095
thicknessCorrection_low: 0.3
thicknessCorrection_high: 0.7

###########################################################################################
# Constant in the model of Doerner and Nix (1986) - DOI: 10.1557/JMR.1986.0601
# By default alpha = 0.25 in Doerner and Nix paper
alpha_min_DoernerNix: 0
alpha_max_DoernerNix: 0.5

###########################################################################################
# Constant in the model of Perriot et al. (2003) - DOI: 10.1557/jmr.2004.19.2.600
n_min_Perriot: 1
n_max_Perriot: 1.4

###########################################################################################
# Constant in the model of Hay et al. (2011) - DOI: 10.1557/jmr.2011.8
F_Hay: 0.626

###########################################################################################
# Constant in the model of Mencik et al. (1997) - DOI: 10.1557/JMR.1997.0327
alpha_min_Mencik: -10000
alpha_max_Mencik: 10000

###########################################################################################
# Constants in the elastic model of Jung et al. (2004) - DOI: 10.1557/JMR.2004.0380
A_Jung: 3.76
B_Jung: 1.38

###########################################################################################
# Constant in the plastic model of Kao and Byrne (1981) - DOI: 10.1111/j.1460-2695.1980.tb01367.x
k_Kao: 0.09

###########################################################################################
# Options for the least square method of Matlab used to fit experimental curves
TolFun_value: 1e-20
TolX_value: 1e-20
MaxIter_value: 10000
Min_YoungModulus: 0 #in GPa
Max_YoungModulus: 1000 #in GPa
Min_Hardness: 0 #in GPa
Max_Hardness: 100 #in GPa