# Copyright 2014 MERCIER David
# Be careful to put a comma + a space between each data...! (YAML convention)
#################################################################################
# Constants given by Loubet et al. (1986) - DOI: 10.1520/STP889-EB
alpha_Loubet: 1.24

#################################################################################
# Constants given by Oliver et al. (1992) - DOI: 10.1557/JMR.1992.1564
epsilonParaboloidRevolution_OliverPharr: 0.75
epsilonConical_OliverPharr: 0.72
epsilonFlatPunch_OliverPharr: 1

# Constants given by Merle et al. (2012) - DOI: 10.1557/jmr.2011.245
epsilon_Merle: 0.76

#################################################################################
# Constants given by King (1987) - DOI: 10.1016/0020-7683(87)90116-8
betaBerkovich_King: 1.034
betaVickers_King: 1.012
betaConical_King: 1.000

# Constants given by Troyon et al. (2002) - DOI: 10.1080/14786430600606834
betaBerkovich_Troyon: 1.062

#################################################################################
# Constants given by Pharr et al. (2009) - DOI: 10.1557/jmr.2009.0096
CSM_K_Pharr: 0.757
CSM_m_Pharr: 1.380